name: docgen from Jira
on: workflow_dispatch

jobs:
   generate:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Set up pandoc
        uses: pandoc/actions/setup@v1

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: docugen
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
        run: |
          docsteady  --namespace DM generate-tpr --trace true LVV-P90  DMTR-331.tex
        shell: bash

      - name: Create commit
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add attachments jira_imgs
          git commit -am "Update from JIRA."
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}

      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make install-dep DMTR-331.pdf'

      - name: Landing page upload
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf DMTR-331.pdf --lsstdoc DMTR-331.tex --extra-download LVV-T2339.pdf --extra-download LVV-T2338.pdf --ltd-product dmtr-331

